import Head from "next/head";
import Image from "next/image";
import Card from "../components/card";
import Banner from "../components/banner";
import styles from "../styles/Home.module.css";
import coffeeStore from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStore,
    },
  };
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log("Button Working");
  };

  return (
    <div className={styles.container}>
      {/* metadata */}
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Banner component */}
      <main className={styles.main}>
        <Banner
          buttonText="View Stores Nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/coffee.svg" height={400} width={400} />
        </div>
        {/* cards */}
        <div className={styles.cardLayout}>
          {props.coffeeStore.map((coffeeStore) => {
            return (
              <Card
                key={coffeeStore.id}
                name={coffeeStore.name}
                imgUrl={coffeeStore.imgUrl}
                className={styles.card}
                href={`/coffee-store/${coffeeStore.id}`}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
}
